#pragma once

#include <tuple>
#include <string>
#include <vector>

#include "UcExport.inl"//UCTOOLDYNAMIC

// VS2015에서 정의되지 않은 Windows API 오류 상수들 정의
#ifdef _MSC_VER
#if _MSC_VER <= 1900  // VS2015 포함 이하 버전
#ifndef ERROR_CAPAUTHZ_NO_POLICY
#define ERROR_CAPAUTHZ_NO_POLICY 454L
#endif
#ifndef ERROR_CAPAUTHZ_DB_CORRUPTED
#define ERROR_CAPAUTHZ_DB_CORRUPTED 455L
#endif
#ifndef ERROR_CAPAUTHZ_SCCD_INVALID_CATALOG
#define ERROR_CAPAUTHZ_SCCD_INVALID_CATALOG 456L
#endif
#ifndef ERROR_CAPAUTHZ_SCCD_NO_AUTH_ENTITY
#define ERROR_CAPAUTHZ_SCCD_NO_AUTH_ENTITY 457L
#endif
#ifndef ERROR_CAPAUTHZ_SCCD_PARSE_ERROR
#define ERROR_CAPAUTHZ_SCCD_PARSE_ERROR 458L
#endif
#ifndef ERROR_CAPAUTHZ_SCCD_DEV_MODE_REQUIRED
#define ERROR_CAPAUTHZ_SCCD_DEV_MODE_REQUIRED 459L
#endif
#ifndef ERROR_CAPAUTHZ_SCCD_NO_CAPABILITY_MATCH
#define ERROR_CAPAUTHZ_SCCD_NO_CAPABILITY_MATCH 460L
#endif
#ifndef ERROR_CIMFS_IMAGE_CORRUPT
#define ERROR_CIMFS_IMAGE_CORRUPT 470L
#endif
#ifndef ERROR_PNP_QUERY_REMOVE_DEVICE_TIMEOUT
#define ERROR_PNP_QUERY_REMOVE_DEVICE_TIMEOUT 480L
#endif
#ifndef ERROR_PNP_QUERY_REMOVE_RELATED_DEVICE_TIMEOUT
#define ERROR_PNP_QUERY_REMOVE_RELATED_DEVICE_TIMEOUT 481L
#endif
#ifndef ERROR_PNP_QUERY_REMOVE_UNRELATED_DEVICE_TIMEOUT
#define ERROR_PNP_QUERY_REMOVE_UNRELATED_DEVICE_TIMEOUT 482L
#endif
#ifndef ERROR_DEVICE_HARDWARE_ERROR
#define ERROR_DEVICE_HARDWARE_ERROR 483L
#endif
#ifndef ERROR_INVALID_ADDRESS
#define ERROR_INVALID_ADDRESS 487L
#endif
#ifndef ERROR_HAS_SYSTEM_CRITICAL_FILES
#define ERROR_HAS_SYSTEM_CRITICAL_FILES 488L
#endif
#ifndef ERROR_PARTITION_TERMINATING
#define ERROR_PARTITION_TERMINATING 1184L
#endif

// 이하 값은 구버전 SDK에 없는 상수들: 컴파일 목적의 대체값
#ifndef ERROR_FILE_METADATA_OPTIMIZATION_IN_PROGRESS
#define ERROR_FILE_METADATA_OPTIMIZATION_IN_PROGRESS 60001L
#endif
#ifndef ERROR_QUOTA_ACTIVITY
#define ERROR_QUOTA_ACTIVITY 60002L
#endif
#ifndef ERROR_HANDLE_REVOKED
#define ERROR_HANDLE_REVOKED 60003L
#endif
#ifndef ERROR_CALLBACK_INVOKE_INLINE
#define ERROR_CALLBACK_INVOKE_INLINE 60004L
#endif
#ifndef ERROR_CPU_SET_INVALID
#define ERROR_CPU_SET_INVALID 60005L
#endif
#ifndef ERROR_ENCLAVE_NOT_TERMINATED
#define ERROR_ENCLAVE_NOT_TERMINATED 60006L
#endif
#ifndef ERROR_ENCLAVE_VIOLATION
#define ERROR_ENCLAVE_VIOLATION 60007L
#endif
#ifndef ERROR_SMB_GUEST_LOGON_BLOCKED
#define ERROR_SMB_GUEST_LOGON_BLOCKED 60008L
#endif
#ifndef ERROR_CONTAINER_ASSIGNED
#define ERROR_CONTAINER_ASSIGNED 60009L
#endif
#ifndef ERROR_JOB_NO_CONTAINER
#define ERROR_JOB_NO_CONTAINER 60010L
#endif
#ifndef ERROR_NOT_SAME_OBJECT
#define ERROR_NOT_SAME_OBJECT 60011L
#endif
#ifndef ERROR_STRICT_CFG_VIOLATION
#define ERROR_STRICT_CFG_VIOLATION 60012L
#endif
#ifndef ERROR_SET_CONTEXT_DENIED
#define ERROR_SET_CONTEXT_DENIED 60013L
#endif
#ifndef ERROR_CROSS_PARTITION_VIOLATION
#define ERROR_CROSS_PARTITION_VIOLATION 60014L
#endif
#ifndef ERROR_RETURN_ADDRESS_HIJACK_ATTEMPT
#define ERROR_RETURN_ADDRESS_HIJACK_ATTEMPT 60015L
#endif
#ifndef RPC_S_DO_NOT_DISTURB
#define RPC_S_DO_NOT_DISTURB 60016L
#endif
#ifndef RPC_S_SYSTEM_HANDLE_COUNT_EXCEEDED
#define RPC_S_SYSTEM_HANDLE_COUNT_EXCEEDED 60017L
#endif
#ifndef RPC_S_SYSTEM_HANDLE_TYPE_MISMATCH
#define RPC_S_SYSTEM_HANDLE_TYPE_MISMATCH 60018L
#endif
#ifndef ERROR_LOST_MODE_LOGON_RESTRICTION
#define ERROR_LOST_MODE_LOGON_RESTRICTION 60019L
#endif
#ifndef ERROR_APPEXEC_CONDITION_NOT_SATISFIED
#define ERROR_APPEXEC_CONDITION_NOT_SATISFIED 60020L
#endif
#ifndef ERROR_APPEXEC_HANDLE_INVALIDATED
#define ERROR_APPEXEC_HANDLE_INVALIDATED 60021L
#endif
#ifndef ERROR_APPEXEC_INVALID_HOST_GENERATION
#define ERROR_APPEXEC_INVALID_HOST_GENERATION 60022L
#endif
#ifndef ERROR_APPEXEC_UNEXPECTED_PROCESS_REGISTRATION
#define ERROR_APPEXEC_UNEXPECTED_PROCESS_REGISTRATION 60023L
#endif
#ifndef ERROR_APPEXEC_INVALID_HOST_STATE
#define ERROR_APPEXEC_INVALID_HOST_STATE 60024L
#endif
#ifndef ERROR_APPEXEC_NO_DONOR
#define ERROR_APPEXEC_NO_DONOR 60025L
#endif
#ifndef ERROR_APPEXEC_HOST_ID_MISMATCH
#define ERROR_APPEXEC_HOST_ID_MISMATCH 60026L
#endif
#ifndef ERROR_APPEXEC_UNKNOWN_USER
#define ERROR_APPEXEC_UNKNOWN_USER 60027L
#endif
#ifndef ERROR_REPARSE_POINT_ENCOUNTERED
#define ERROR_REPARSE_POINT_ENCOUNTERED 60028L
#endif
#ifndef ERROR_SECUREBOOT_POLICY_NOT_AUTHORIZED
#define ERROR_SECUREBOOT_POLICY_NOT_AUTHORIZED 60029L
#endif
#ifndef ERROR_SECUREBOOT_POLICY_UNKNOWN
#define ERROR_SECUREBOOT_POLICY_UNKNOWN 60030L
#endif
#ifndef ERROR_SECUREBOOT_POLICY_MISSING_ANTIROLLBACKVERSION
#define ERROR_SECUREBOOT_POLICY_MISSING_ANTIROLLBACKVERSION 60031L
#endif
#ifndef ERROR_SECUREBOOT_PLATFORM_ID_MISMATCH
#define ERROR_SECUREBOOT_PLATFORM_ID_MISMATCH 60032L
#endif
#ifndef ERROR_SECUREBOOT_POLICY_ROLLBACK_DETECTED
#define ERROR_SECUREBOOT_POLICY_ROLLBACK_DETECTED 60033L
#endif
#ifndef ERROR_SECUREBOOT_POLICY_UPGRADE_MISMATCH
#define ERROR_SECUREBOOT_POLICY_UPGRADE_MISMATCH 60034L
#endif
#ifndef ERROR_SECUREBOOT_REQUIRED_POLICY_FILE_MISSING
#define ERROR_SECUREBOOT_REQUIRED_POLICY_FILE_MISSING 60035L
#endif
#ifndef ERROR_SECUREBOOT_NOT_BASE_POLICY
#define ERROR_SECUREBOOT_NOT_BASE_POLICY 60036L
#endif
#ifndef ERROR_SECUREBOOT_NOT_SUPPLEMENTAL_POLICY
#define ERROR_SECUREBOOT_NOT_SUPPLEMENTAL_POLICY 60037L
#endif
#ifndef ERROR_ALREADY_HAS_STREAM_ID
#define ERROR_ALREADY_HAS_STREAM_ID 60038L
#endif
#ifndef ERROR_SMR_GARBAGE_COLLECTION_REQUIRED
#define ERROR_SMR_GARBAGE_COLLECTION_REQUIRED 60039L
#endif
#ifndef ERROR_WOF_WIM_HEADER_CORRUPT
#define ERROR_WOF_WIM_HEADER_CORRUPT 60040L
#endif
#ifndef ERROR_WOF_WIM_RESOURCE_TABLE_CORRUPT
#define ERROR_WOF_WIM_RESOURCE_TABLE_CORRUPT 60041L
#endif
#ifndef ERROR_WOF_FILE_RESOURCE_TABLE_CORRUPT
#define ERROR_WOF_FILE_RESOURCE_TABLE_CORRUPT 60042L
#endif
#ifndef ERROR_SYSTEM_INTEGRITY_ROLLBACK_DETECTED
#define ERROR_SYSTEM_INTEGRITY_ROLLBACK_DETECTED 60043L
#endif
#ifndef ERROR_SYSTEM_INTEGRITY_POLICY_VIOLATION
#define ERROR_SYSTEM_INTEGRITY_POLICY_VIOLATION 60044L
#endif
#ifndef ERROR_SYSTEM_INTEGRITY_INVALID_POLICY
#define ERROR_SYSTEM_INTEGRITY_INVALID_POLICY 60045L
#endif
#ifndef ERROR_SYSTEM_INTEGRITY_POLICY_NOT_SIGNED
#define ERROR_SYSTEM_INTEGRITY_POLICY_NOT_SIGNED 60046L
#endif
#ifndef ERROR_SYSTEM_INTEGRITY_TOO_MANY_POLICIES
#define ERROR_SYSTEM_INTEGRITY_TOO_MANY_POLICIES 60047L
#endif
#ifndef ERROR_SYSTEM_INTEGRITY_SUPPLEMENTAL_POLICY_NOT_AUTHORIZED
#define ERROR_SYSTEM_INTEGRITY_SUPPLEMENTAL_POLICY_NOT_AUTHORIZED 60048L
#endif
#ifndef ERROR_VSM_NOT_INITIALIZED
#define ERROR_VSM_NOT_INITIALIZED 60049L
#endif
#ifndef ERROR_VSM_DMA_PROTECTION_NOT_IN_USE
#define ERROR_VSM_DMA_PROTECTION_NOT_IN_USE 60050L
#endif
#ifndef ERROR_PLATFORM_MANIFEST_NOT_AUTHORIZED
#define ERROR_PLATFORM_MANIFEST_NOT_AUTHORIZED 60051L
#endif
#ifndef ERROR_PLATFORM_MANIFEST_INVALID
#define ERROR_PLATFORM_MANIFEST_INVALID 60052L
#endif
#ifndef ERROR_PLATFORM_MANIFEST_FILE_NOT_AUTHORIZED
#define ERROR_PLATFORM_MANIFEST_FILE_NOT_AUTHORIZED 60053L
#endif
#ifndef ERROR_PLATFORM_MANIFEST_CATALOG_NOT_AUTHORIZED
#define ERROR_PLATFORM_MANIFEST_CATALOG_NOT_AUTHORIZED 60054L
#endif
#ifndef ERROR_PLATFORM_MANIFEST_BINARY_ID_NOT_FOUND
#define ERROR_PLATFORM_MANIFEST_BINARY_ID_NOT_FOUND 60055L
#endif
#ifndef ERROR_PLATFORM_MANIFEST_NOT_ACTIVE
#define ERROR_PLATFORM_MANIFEST_NOT_ACTIVE 60056L
#endif
#ifndef ERROR_PLATFORM_MANIFEST_NOT_SIGNED
#define ERROR_PLATFORM_MANIFEST_NOT_SIGNED 60057L
#endif
#ifndef ERROR_CLUSTER_UPGRADE_INCOMPATIBLE_VERSIONS
#define ERROR_CLUSTER_UPGRADE_INCOMPATIBLE_VERSIONS 60058L
#endif
#ifndef ERROR_CLUSTER_UPGRADE_FIX_QUORUM_NOT_SUPPORTED
#define ERROR_CLUSTER_UPGRADE_FIX_QUORUM_NOT_SUPPORTED 60059L
#endif
#ifndef ERROR_CLUSTER_UPGRADE_RESTART_REQUIRED
#define ERROR_CLUSTER_UPGRADE_RESTART_REQUIRED 60060L
#endif
#ifndef ERROR_CLUSTER_UPGRADE_IN_PROGRESS
#define ERROR_CLUSTER_UPGRADE_IN_PROGRESS 60061L
#endif
#ifndef ERROR_CLUSTER_UPGRADE_INCOMPLETE
#define ERROR_CLUSTER_UPGRADE_INCOMPLETE 60062L
#endif
#ifndef ERROR_CLUSTER_NODE_IN_GRACE_PERIOD
#define ERROR_CLUSTER_NODE_IN_GRACE_PERIOD 60063L
#endif
#ifndef ERROR_CLUSTER_CSV_IO_PAUSE_TIMEOUT
#define ERROR_CLUSTER_CSV_IO_PAUSE_TIMEOUT 60064L
#endif
#ifndef ERROR_NODE_NOT_ACTIVE_CLUSTER_MEMBER
#define ERROR_NODE_NOT_ACTIVE_CLUSTER_MEMBER 60065L
#endif
#ifndef ERROR_CLUSTER_RESOURCE_NOT_MONITORED
#define ERROR_CLUSTER_RESOURCE_NOT_MONITORED 60066L
#endif
#ifndef ERROR_CLUSTER_RESOURCE_DOES_NOT_SUPPORT_UNMONITORED
#define ERROR_CLUSTER_RESOURCE_DOES_NOT_SUPPORT_UNMONITORED 60067L
#endif
#ifndef ERROR_CLUSTER_RESOURCE_IS_REPLICATED
#define ERROR_CLUSTER_RESOURCE_IS_REPLICATED 60068L
#endif
#ifndef ERROR_CLUSTER_NODE_ISOLATED
#define ERROR_CLUSTER_NODE_ISOLATED 60069L
#endif
#ifndef ERROR_CLUSTER_NODE_QUARANTINED
#define ERROR_CLUSTER_NODE_QUARANTINED 60070L
#endif
#ifndef ERROR_CLUSTER_DATABASE_UPDATE_CONDITION_FAILED
#define ERROR_CLUSTER_DATABASE_UPDATE_CONDITION_FAILED 60071L
#endif
#ifndef ERROR_CLUSTER_SPACE_DEGRADED
#define ERROR_CLUSTER_SPACE_DEGRADED 60072L
#endif
#ifndef ERROR_CLUSTER_TOKEN_DELEGATION_NOT_SUPPORTED
#define ERROR_CLUSTER_TOKEN_DELEGATION_NOT_SUPPORTED 60073L
#endif
#ifndef ERROR_CLUSTER_CSV_INVALID_HANDLE
#define ERROR_CLUSTER_CSV_INVALID_HANDLE 60074L
#endif
#ifndef ERROR_CLUSTER_CSV_SUPPORTED_ONLY_ON_COORDINATOR
#define ERROR_CLUSTER_CSV_SUPPORTED_ONLY_ON_COORDINATOR 60075L
#endif
#ifndef ERROR_GROUPSET_NOT_AVAILABLE
#define ERROR_GROUPSET_NOT_AVAILABLE 60076L
#endif
#ifndef ERROR_GROUPSET_NOT_FOUND
#define ERROR_GROUPSET_NOT_FOUND 60077L
#endif
#ifndef ERROR_GROUPSET_CANT_PROVIDE
#define ERROR_GROUPSET_CANT_PROVIDE 60078L
#endif
#ifndef ERROR_CLUSTER_FAULT_DOMAIN_PARENT_NOT_FOUND
#define ERROR_CLUSTER_FAULT_DOMAIN_PARENT_NOT_FOUND 60079L
#endif
#ifndef ERROR_CLUSTER_FAULT_DOMAIN_INVALID_HIERARCHY
#define ERROR_CLUSTER_FAULT_DOMAIN_INVALID_HIERARCHY 60080L
#endif
#ifndef ERROR_CLUSTER_FAULT_DOMAIN_FAILED_S2D_VALIDATION
#define ERROR_CLUSTER_FAULT_DOMAIN_FAILED_S2D_VALIDATION 60081L
#endif
#ifndef ERROR_CLUSTER_FAULT_DOMAIN_S2D_CONNECTIVITY_LOSS
#define ERROR_CLUSTER_FAULT_DOMAIN_S2D_CONNECTIVITY_LOSS 60082L
#endif
#ifndef ERROR_CLUSTER_INVALID_INFRASTRUCTURE_FILESERVER_NAME
#define ERROR_CLUSTER_INVALID_INFRASTRUCTURE_FILESERVER_NAME 60083L
#endif
#ifndef ERROR_CLUSTERSET_MANAGEMENT_CLUSTER_UNREACHABLE
#define ERROR_CLUSTERSET_MANAGEMENT_CLUSTER_UNREACHABLE 60084L
#endif
#define ERROR_NO_WORK_DONE 235L
#define ERROR_COMPRESSION_NOT_BENEFICIAL 344L
#define ERROR_STORAGE_TOPOLOGY_ID_MISMATCH 345L
#define ERROR_BLOCKED_BY_PARENTAL_CONTROLS 346L
#define ERROR_BLOCK_TOO_MANY_REFERENCES 347L
#define ERROR_MARKED_TO_DISALLOW_WRITES 348L
#define ERROR_ENCLAVE_FAILURE 349L
#define ERROR_NETWORK_ACCESS_DENIED_EDP 354L
#define ERROR_DEVICE_HINT_NAME_BUFFER_TOO_SMALL 355L
#define ERROR_EDP_POLICY_DENIES_OPERATION 356L
#define ERROR_EDP_DPL_POLICY_CANT_BE_SATISFIED 357L
#define ERROR_CLOUD_FILE_SYNC_ROOT_METADATA_CORRUPT 358L
#define ERROR_DEVICE_IN_MAINTENANCE 359L
#define ERROR_NOT_SUPPORTED_ON_DAX 360L
#define ERROR_DAX_MAPPING_EXISTS 361L
#define ERROR_CLOUD_FILE_PROVIDER_NOT_RUNNING 362L
#define ERROR_CLOUD_FILE_METADATA_CORRUPT 363L
#define ERROR_CLOUD_FILE_METADATA_TOO_LARGE 364L
#define ERROR_CLOUD_FILE_PROPERTY_BLOB_TOO_LARGE 365L
#define ERROR_CLOUD_FILE_PROPERTY_BLOB_CHECKSUM_MISMATCH 366L
#define ERROR_CHILD_PROCESS_BLOCKED 367L
#define ERROR_STORAGE_LOST_DATA_PERSISTENCE 368L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_UNAVAILABLE 369L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_METADATA_CORRUPT 370L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_BUSY 371L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_PROVIDER_UNKNOWN 372L
#define ERROR_GDI_HANDLE_LEAK 373L
#define ERROR_CLOUD_FILE_TOO_MANY_PROPERTY_BLOBS 374L
#define ERROR_CLOUD_FILE_PROPERTY_VERSION_NOT_SUPPORTED 375L
#define ERROR_NOT_A_CLOUD_FILE 376L
#define ERROR_CLOUD_FILE_NOT_IN_SYNC 377L
#define ERROR_CLOUD_FILE_ALREADY_CONNECTED 378L
#define ERROR_CLOUD_FILE_NOT_SUPPORTED 379L
#define ERROR_CLOUD_FILE_INVALID_REQUEST 380L
#define ERROR_CLOUD_FILE_READ_ONLY_VOLUME 381L
#define ERROR_CLOUD_FILE_CONNECTED_PROVIDER_ONLY 382L
#define ERROR_CLOUD_FILE_VALIDATION_FAILED 383L
#define ERROR_SMB1_NOT_AVAILABLE 384L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_INVALID_OPERATION 385L
#define ERROR_CLOUD_FILE_AUTHENTICATION_FAILED 386L
#define ERROR_CLOUD_FILE_INSUFFICIENT_RESOURCES 387L
#define ERROR_CLOUD_FILE_NETWORK_UNAVAILABLE 388L
#define ERROR_CLOUD_FILE_UNSUCCESSFUL 389L
#define ERROR_CLOUD_FILE_NOT_UNDER_SYNC_ROOT 390L
#define ERROR_CLOUD_FILE_IN_USE 391L
#define ERROR_CLOUD_FILE_PINNED 392L
#define ERROR_CLOUD_FILE_REQUEST_ABORTED 393L
#define ERROR_CLOUD_FILE_PROPERTY_CORRUPT 394L
#define ERROR_CLOUD_FILE_ACCESS_DENIED 395L
#define ERROR_CLOUD_FILE_INCOMPATIBLE_HARDLINKS 396L
#define ERROR_CLOUD_FILE_PROPERTY_LOCK_CONFLICT 397L
#define ERROR_CLOUD_FILE_REQUEST_CANCELED 398L
#define ERROR_EXTERNAL_SYSKEY_NOT_SUPPORTED 399L
#define ERROR_CLOUD_FILE_PROVIDER_TERMINATED 404L
#define ERROR_NOT_A_CLOUD_SYNC_ROOT 405L
#define ERROR_FILE_PROTECTED_UNDER_DPL 406L
#define ERROR_VOLUME_NOT_CLUSTER_ALIGNED 407L
#define ERROR_NO_PHYSICALLY_ALIGNED_FREE_SPACE_FOUND 408L
#define ERROR_APPX_FILE_NOT_ENCRYPTED 409L
#define ERROR_RWRAW_ENCRYPTED_FILE_NOT_ENCRYPTED 410L
#define ERROR_RWRAW_ENCRYPTED_INVALID_EDATAINFO_FILEOFFSET 411L
#define ERROR_RWRAW_ENCRYPTED_INVALID_EDATAINFO_FILERANGE 412L
#define ERROR_RWRAW_ENCRYPTED_INVALID_EDATAINFO_PARAMETER 413L
#define ERROR_LINUX_SUBSYSTEM_NOT_PRESENT 414L
#define ERROR_FT_READ_FAILURE 415L
#define ERROR_STORAGE_RESERVE_ID_INVALID 416L
#define ERROR_STORAGE_RESERVE_DOES_NOT_EXIST 417L
#define ERROR_STORAGE_RESERVE_ALREADY_EXISTS 418L
#define ERROR_STORAGE_RESERVE_NOT_EMPTY 419L
#define ERROR_NOT_A_DAX_VOLUME 420L
#define ERROR_NOT_DAX_MAPPABLE 421L
#define ERROR_TIME_SENSITIVE_THREAD 422L
#define ERROR_DPL_NOT_SUPPORTED_FOR_USER 423L
#define ERROR_CASE_DIFFERING_NAMES_IN_DIR 424L
#define ERROR_FILE_NOT_SUPPORTED 425L
#define ERROR_CLOUD_FILE_REQUEST_TIMEOUT 426L
#define ERROR_NO_TASK_QUEUE 427L
#define ERROR_SRC_SRV_DLL_LOAD_FAILED 428L
#define ERROR_NOT_SUPPORTED_WITH_BTT 429L
#define ERROR_ENCRYPTION_DISABLED 430L
#define ERROR_ENCRYPTING_METADATA_DISALLOWED 431L
#define ERROR_CANT_CLEAR_ENCRYPTION_FLAG 432L
#define ERROR_NO_SUCH_DEVICE 433L
#define ERROR_CLOUD_FILE_DEHYDRATION_DISALLOWED 434L
#define ERROR_FILE_SNAP_IN_PROGRESS 435L
#define ERROR_FILE_SNAP_USER_SECTION_NOT_SUPPORTED 436L
#define ERROR_FILE_SNAP_MODIFY_NOT_SUPPORTED 437L
#define ERROR_FILE_SNAP_IO_NOT_COORDINATED 438L
#define ERROR_FILE_SNAP_UNEXPECTED_ERROR 439L
#define ERROR_FILE_SNAP_INVALID_PARAMETER 440L
#define ERROR_UNSATISFIED_DEPENDENCIES 441L
#define ERROR_CASE_SENSITIVE_PATH 442L
#define ERROR_UNEXPECTED_NTCACHEMANAGER_ERROR 443L
#define ERROR_LINUX_SUBSYSTEM_UPDATE_REQUIRED 444L
#define ERROR_DLP_POLICY_WARNS_AGAINST_OPERATION 445L
#define ERROR_DLP_POLICY_DENIES_OPERATION 446L
#define ERROR_DLP_POLICY_SILENTLY_FAIL 449L
#define ERROR_CAPAUTHZ_NOT_DEVUNLOCKED 450L
#define ERROR_CAPAUTHZ_CHANGE_TYPE 451L
#define ERROR_CAPAUTHZ_NOT_PROVISIONED 452L
#define ERROR_CAPAUTHZ_NOT_AUTHORIZED 453L
#endif
#endif

class CEditCtrlCV : public CEdit
{
public:
	virtual BOOL PreTranslateMessage(MSG* pMsg)
		//BOOL CEditCtrlCV::PreTranslateMessage(MSG* pMsg)
	{
		switch (pMsg->message)
		{
		case WM_KEYDOWN:
		{
			short ctrl = ::GetKeyState(VK_CONTROL);
			if (ctrl < 0)
			{
				switch (pMsg->wParam)
				{
				case 'Z':this->Undo();
					return TRUE;
				case 'X':this->Cut();
					return TRUE;
				case 'C':
				{
					int sc = -1, ec = -1;
					this->GetSel(sc, ec);
					if (sc == -1 && ec == -1)
						this->SetSel(0, -1);
					this->Copy();
					return TRUE;
				}
				case 'V':this->Paste();
					return TRUE;
				case 'A':this->SetSel(0, -1);
					return TRUE;
				}
			}
		}
		}
		return __super::PreTranslateMessage(pMsg);
	}
};


inline BOOL IsRealWindow(CWnd* pw, BOOL bVisible = FALSE)
{
	return pw && pw->GetSafeHwnd() && ::IsWindow(pw->GetSafeHwnd()) && (!bVisible || pw->IsWindowVisible());
}
inline BOOL IsRealWindow(CWnd& rw, BOOL bVisible = FALSE)
{
	return IsRealWindow(&rw, bVisible);
}

UCTOOLDYNAMIC void UcSetListReportStyle(CListCtrl* pList, DWORD dwStyle = LVS_SHOWSELALWAYS | LVS_SINGLESEL, DWORD dwExStyle = LVS_EX_FULLROWSELECT | LVS_EX_GRIDLINES);

UCTOOLDYNAMIC void UcSetListColumn(CListCtrl* pList, std::initializer_list<std::tuple<int, LPARAM, int, CString>> tuples);

enum ELC_
{
	eLc_None,
	eLc_Clear,
	eLc_Unselect,
};
int UcSelectListItemEx(CListCtrl* pl, int curSel, bool bShow = true);
//void UcSelectListItem(CListCtrl& pl, int iItem, bool bShow = true);
void UcSelectListItem(CListCtrl* pl, int iItem, bool bShow = true, int iOp = eLc_None);
void UcFocusListItem(CListCtrl* pl, int iItem);
UCTOOLDYNAMIC int UcGetSelectedListItem(CListCtrl* pl);
int UcGetSelectedListItem(CListCtrl* pl, CDWordArray& ar);
int UcGetSelectedCount(CListCtrl* pl);
int UcClearSelectedListItem(CListCtrl* pl);

UCTOOLDYNAMIC void UcSetWindowStyle(HWND hWnd, long style, BOOL bSetBit = TRUE, bool bEx = false);
UCTOOLDYNAMIC void UcSavePosition();
UCTOOLDYNAMIC BOOL UcLoadPosition(CWnd* pWnd);

UCTOOLDYNAMIC void UcEnableWindow(CWnd* pw, CWnd* ctrl, BOOL bEnable = TRUE);
UCTOOLDYNAMIC void UcEnableWindow(CWnd* pw, int idc, BOOL bEnable = TRUE);
UCTOOLDYNAMIC void UcEnableWindow(CWnd* pw, std::initializer_list<int> arIdc, BOOL bEnable = TRUE);
UCTOOLDYNAMIC void UcEnableWindow(CWnd* pw, const int* idc, int cnt, BOOL bEnable = TRUE);
// idc vs BOOL 각각 쌍으로 하는 경우
UCTOOLDYNAMIC void UcEnableWindow(CWnd* pw, const int* idc, BOOL* bEnable, int cnt);
UCTOOLDYNAMIC void UcEnableWindow(CWnd* pw, std::initializer_list<std::pair<int, BOOL>> arIdcBool);


BOOL UcIsScrollBarAtBottom(CWnd* pWnd, int hFont = 14);

int UcFindStrFromListCtrlItemData(CListCtrl* pList, LPCWSTR sData);

UCTOOLDYNAMIC SYSTEMTIME UcGetItemDateTime(CDateTimeCtrl* cDate, CDateTimeCtrl* cTime);
UCTOOLDYNAMIC void UcSetItemDateTime(SYSTEMTIME st, CDateTimeCtrl* cDate, CDateTimeCtrl* cTime);

void UcSimulateMouseDoubleClick(int x, int y);




/// 변수명이 JSON 키 이므로 _value처럼 앞에 '_'가 안 붙을 수 있으므로 IDC_## 이다. IDC## 가 아님.
/// JObj& jbj = 뭔가 있어야 한다.
///DDX_Check(CDataExchange* pDX, int nIDC, int& value);
/// 변수명이 반드시 _value처럼 앞에 '_'가 있어야 한다.
#define KDDX_Text(field)  DDX_Text( pDX, IDC##field, doc->field)
#define KDDX_CBBox(field) DDX_CBString(pDX, IDC##field, doc->field)
#define KDDX_Radio(field) DDX_Radio(pDX, IDC##field, doc->field)
#define KDDX_Check(field) DDX_Check(pDX, IDC##field, doc->field)

#define KDDX_TextA(field)  { if(pDX->m_bSaveAndValidate) { CStringW v; \
    DDX_Text(pDX, IDC##field, v); doc->field = CStringA(v);} else { \
    CStringW v(doc->field);\
    DDX_Text(pDX, IDC##field, v); }}

#define KDDX_CBBoxA(field) { if(pDX->m_bSaveAndValidate) { CStringW v;\
	DDX_CBString(pDX, IDC##field, v); doc->field = CStringA(v);} else { \
    CStringW v(doc->field);\
    DDX_CBString(pDX, IDC##field, v); }}


/// 변수명이 JSON 키 이므로 _value처럼 앞에 '_'가 안 붙을 수 있으므로 IDC_## 이다. IDC## 가 아님.
/// JObj& jbj = 뭔가 있어야 한다.

#define KDDXJM_IntTok(field, tok) {\
	if(!pDX->m_bSaveAndValidate) field = jbj.I(#field); \
	DDX_Text(pDX, IDC##tok##field, field);\
	if(pDX->m_bSaveAndValidate) jbj(#field) = field;}
#define KDDXJ_IntTok(field, tok) {int v;\
	if(!pDX->m_bSaveAndValidate) v = jbj.I(#field); \
	DDX_Text(pDX, IDC##tok##field, v);\
	if(pDX->m_bSaveAndValidate) jbj(#field) = v;}

#define KDDXJM_TextTok(field, tok) {\
	if(!pDX->m_bSaveAndValidate) field = jbj.S(#field); \
	DDX_Text(pDX, IDC##tok##field, field);\
	if(pDX->m_bSaveAndValidate) jbj(#field) = field;}
#define KDDXJ_TextTok(field, tok) {CStringW v;\
	if(!pDX->m_bSaveAndValidate) v = jbj.S(#field); \
	DDX_Text(pDX, IDC##tok##field, v);\
	if(pDX->m_bSaveAndValidate) jbj(#field) = v;}
//#define KDDXJ_TextATok(field, tok) KDDXJ_TextTok(field, tok)

#define KDDXJM_CBBoxTok(field, tok) {\
	if(!pDX->m_bSaveAndValidate) field = jbj.S(#field); \
	DDX_CBString(pDX, IDC##tok##field, field);\
	if(pDX->m_bSaveAndValidate) jbj(#field) = field;}
#define KDDXJ_CBBoxTok(field, tok) {CStringW v;\
	if(!pDX->m_bSaveAndValidate) v = jbj.S(#field); \
	DDX_CBString(pDX, IDC##tok##field, v);\
	if(pDX->m_bSaveAndValidate) jbj(#field) = v;}


/// bool 로 저장 안하는 이유는 0, 1 말고 2이상의 값이 라디로버튼이나 체크버튼에서 나온다.
#define KDDXJM_RadioTok(field, tok) {\
	if(!pDX->m_bSaveAndValidate) field = jbj.I(#field); \
	DDX_Radio(pDX, IDC##tok##field, field); jbj(#field) = field;\
	if(pDX->m_bSaveAndValidate) jbj(#field) = field;}
#define KDDXJ_RadioTok(field, tok) {int v; \
	if(!pDX->m_bSaveAndValidate) v = jbj.I(#field); \
	DDX_Radio(pDX, IDC##tok##field, v); jbj(#field) = v;\
	if(pDX->m_bSaveAndValidate) jbj(#field) = v;}
#define KDDXJM_CheckTok(field, tok) {\
	if(!pDX->m_bSaveAndValidate) field = jbj.I(#field); \
	DDX_Check(pDX, IDC##tok##field, field); jbj(#field) = field;\
	if(pDX->m_bSaveAndValidate) jbj(#field) = field;}
#define KDDXJ_CheckTok(field, tok) {int v; \
	if(!pDX->m_bSaveAndValidate) v = jbj.I(#field); \
	DDX_Check(pDX, IDC##tok##field, v); jbj(#field) = v;\
	if(pDX->m_bSaveAndValidate) jbj(#field) = v;}


#define KDDXJ_Int(field) KDDXJ_IntTok(field, _)
#define KDDXJ_Text(field) KDDXJ_TextTok(field, _)
//#define KDDXJ_TextA(field) KDDXJ_Text(field) // 같다. 아니 JObj내부에 sa로 저장 하지 않는다.
#define KDDXJ_Radio(field) KDDXJ_RadioTok(field, _)
#define KDDXJ_Check(field) KDDXJ_CheckTok(field, _)
#define KDDXJ_CBBox(field) KDDXJ_CBBoxTok(field, _)

///?warning : 매크로 함수와 가로 사이에 공백이 들어 가면 안됨
#define KDDXJM_Int(field) KDDXJM_IntTok(field, _)
#define KDDXJM_Text(field) KDDXJM_TextTok(field, _)
#define KDDXJM_Radio(field) KDDXJM_RadioTok(field, _)
#define KDDXJM_Check(field) KDDXJM_CheckTok(field, _)
#define KDDXJM_CBBox(field) KDDXJM_CBBoxTok(field, _)


#define DDX_IPAddressStr(pDX, IDC, str) {\
	DWORD dwIP{ 0 };\
	if (pDX->m_bSaveAndValidate) {\
		DDX_IPAddress(pDX, IDC, dwIP);\
		str.Format(L"%u.%u.%u.%u", (dwIP >> 24) & 0xFF, (dwIP >> 16) & 0xFF, (dwIP >> 8) & 0xFF, dwIP & 0xFF);\
	} else {\
		DWORD b1{ 0 }, b2{ 0 }, b3{ 0 }, b4{ 0 };\
		swscanf_s(str.GetBuffer(128), L"%u.%u.%u.%u", &b1, &b2, &b3, &b4); str.ReleaseBuffer();\
		dwIP = (b1 & 0xFF) << 24 | (b2 & 0xFF) << 16 | (b3 & 0xFF) << 8 | (b4 & 0xFF);\
		DDX_IPAddress(pDX, IDC, dwIP);\
	}\
}

struct MyMonitorEnumContext {
	std::vector<std::tuple<MONITORINFOEX, UINT, UINT>> monitors;
};
std::shared_ptr<MyMonitorEnumContext> UcGetMonitorInfo();

UCTOOLDYNAMIC void UcMoveWindowToMonitor(CWnd* pWnd, const MONITORINFOEX& mi);


UCTOOLDYNAMIC HWND UcGetMainWnd();
UCTOOLDYNAMIC CWnd* UcGetMainCWnd();
